### PR TITLE
Added reportNS function to I18NextProvider to report used namespaces

### PR DESCRIPTION
**Pull request by olivierpascal**
Related to #499

### CODE REVIEW

**Comment by jamuhl** [comment]
Looks good...would you also be able to extend the documentation?!?:

-> https://react.i18next.com/components/i18nextprovider#the-i-18-nextprovider-props (add the new prop)
-> https://react.i18next.com/misc/serverside-rendering add a small sample (like in your issue description to show how to use this new feature)

**Comment by olivierpascal** [comment]
Sure!

**Comment by olivierpascal** [comment]
Done: https://github.com/i18next/react-i18next-gitbook/pull/20

**Comment by jamuhl** [comment]
thanks again

published in react-i18next@7.11.0

**Comment by olivierpascal** [comment]
Maybe you can create an issue (please tag me) and use something like `yourArray.filter(Boolean)` until a fix is available?

**Pull request merged**
