### PR TITLE
Allow `TFuncKey` to be used without specifying the namespace, in the …

### PR DESCRIPTION
**Pull request by raynor85**
…same way `TFunction` and `useTranslation` work

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Review by pedrodurek — APPROVED** [review]
LGTM! Thanks for your contribution! 🙌

**Comment by jamuhl** [comment]
@raynor85 @pedrodurek there is a breaking test - I'm not sure about what and why - but can't be merged before fixed

**Comment by raynor85** [comment]
> @raynor85 @pedrodurek there is a breaking test - I'm not sure about what and why - but can't be merged before fixed
> 
> https://app.circleci.com/pipelines/github/i18next/react-i18next/582/workflows/2c506949-6fcc-4e30-80ed-c48e049b5711/jobs/526

The same test was failing on my local branch just after I forked the project, before adding my changes.

**Comment by raynor85** [comment]
> > @raynor85 @pedrodurek there is a breaking test - I'm not sure about what and why - but can't be merged before fixed
> > https://app.circleci.com/pipelines/github/i18next/react-i18next/582/workflows/2c506949-6fcc-4e30-80ed-c48e049b5711/jobs/526
> 
> The same test was failing on my local branch just after I forked the project, before adding my changes.

For some weird reason, I just retried locally and all the tests passed. @jamuhl @pedrodurek can any of you retrigger the circleci build? I think it was a temporary failure. I can't do it on my end without pushing other code

**Comment by raynor85** [comment]
It looks like circleci is reusing a corrupted node_module folder as highlighted in the `Restoring cache` section:
```
Found a cache from build 525 at dependency-cache-r9gAW0IGK7w2nqduXpPf_YLxJmRqL7As2VJ56Km4t64=
Size: 39 MiB
Cached paths:
  * /home/circleci/project/node_modules
 ```
I think someone should try to invalidate the cache and rerun the build. Now it runs locally, but it still fails in the remote server.

**Comment by jamuhl** [comment]
not found any way to invalidate that

**Comment by pedrodurek** [comment]
Hey @jamuhl, usually when we cache dependencies on CircleCI we add `v#-` as prefix to the cache key, for instance: `v1-dependency-cache-{{ checksum "package.json" }}`. This way, in case the cached node_modules corrupts, we don't need to wait 15 days for the cached dependencies to become invalid, we can simply bump the version under `restore_cache` and `save_cache`. Like this: `v2-dependency-cache-{{ checksum "package.json" }}`.
[Here](https://circleci.com/docs/2.0/caching/?utm_medium=SEM&utm_source=gnb&utm_campaign=SEM-gb-DSA-Eng-uscan&utm_content=&utm_term=dynamicSearch-&gclid=Cj0KCQiA7NKBBhDBARIsAHbXCB5SV164Fk_Ug0N5LMYTk3x-Qon6qwsP0IBfuc__T3Rue5LASx691GwaAnCfEALw_wcB#clearing-cache) you can find more info about that.

**Comment by pedrodurek** [comment]
To prevent from manually bumping the version in `config.yml` file, you can also create an [environment variable]( https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project), and control the cache version from there. For example:
`${CACHE_VERSION}-dependency-cache-{{ checksum "package.json" }}`

**Comment by raynor85** [comment]
Yeah, I pushed a change in one of the dependency in package.json which forced circleci to run a fresh build, which was successful https://app.circleci.com/pipelines/github/i18next/react-i18next/584/workflows/2c1a055d-b2a4-4dc4-b8da-7142bcc265a3/jobs/531
I then rollback it in another commit, but the cached version for that one is still there. I am afraid that every PR will have the same issue, unless they change a dependency directly

**Comment by raynor85** [comment]
I ended up bumping the dependencies to invalidate the cache. This prevents circleci to cache the corrupted build, and will prevent other contributors to have the same issue if this PR is merged. Ideally this should be handled separately, but this workaround is the best I can do in my power. I hope to see this merged soon :)

**Comment by jamuhl** [comment]
thank you for solving this...

the PR was merged and published in react-i18next@11.8.8

**Pull request merged**
