### PR TITLE
Fix/trans mock in jest example

### PR DESCRIPTION
**Pull request by moT01**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

Closes: #1209

### CODE REVIEW

**Comment by tigerabrodi** [comment]
Looks nice @moT01 :tada: :raised_hands: , also something I wanted to mention is, why `Array.isArray` is better for this case, is because when you check for length only, Maps and Sets do have a length property in JavaScript, therefore it can also be confusing for the reader of the code :+1:

**Comment by adrai** [comment]
lgtm

**Comment by jamuhl** [comment]
thanks to all for helping with this one....

**Comment by moT01** [comment]
Thanks for the quick reviews and merge on this everyone 🎉 I'm having a lot of fun using this package by the way. It's real easy to use - nice job 👍

**Comment by tigerabrodi** [comment]
@moT01 Happy to hear :smiling_face_with_three_hearts: :raised_hands:

**Pull request merged**
