### PR TITLE
Added an option of using the <Interpolate /> with a raw HTML

### PR DESCRIPTION
**Pull request by KostyaEsmukov**
Discussion in #189

Usage:

    <Interpolate i18nKey='foo' useDangerouslySetInnerHTML={true} />

TODO:

- [ ] Tests? I'm not sure how to properly test a component, see my comment at #193 
- [ ] Generate dist files

### CODE REVIEW

**Comment by jamuhl** [comment]
did you init i18next before using it?

**Comment by KostyaEsmukov** [comment]
In my own project? Yes I did, and it works as is. Why do you ask?

In case you need my config, here it is:

    import * as i18n from 'i18next';
    import * as LanguageDetector from 'i18next-browser-languagedetector';

    import { ru } from './ru';

    i18n
      .use(LanguageDetector)
      .init({
        fallbackLng: 'ru',
        whitelist: ['ru'],

        debug: ENV !== 'production',

        interpolation: {
          prefix: '__',
          suffix: '__',
          escapeValue: false  // not needed for react!!
        },
        joinArrays: '\n',
        resources: {
          ru: {
            translation: ru
          }
        }
      });

**Comment by jamuhl** [comment]
sorry landed on wrong PR...did reply on phone while on holiday network...seems mail reply mixed it up...will review PR after holiday.

**Comment by jamuhl** [comment]
published react-i18next@1.7.0. thanks for providing this.

**Pull request merged**
