### PR TITLE
Add typescript tests with example usage as sanity check and hook into `test`script

### LINKED ISSUE #654: Typescript definitions are not tested
**Describe the bug**
Downstream in my app, since the types were brought in-repo - I now have typescript problems related to i18next/react-i18next.  This may be a local problem, or one with the repo, but without tests in the repo I have no certainty.

Tests were used in the @types/react-i18next but never brought here e.g. [`react-i18next-tests.tsx`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29945/files)

**Occurs in react-i18next version**
 react-i18next  ^9.0.0
 i18next   ^13.1.0

**TL;DR**

I'm working on a PR with typescript usage tests that will yield some certainty that types will work as represented by examples.  With that in place, it will give me confidence and I can focus on potential userland errors in my environment.

### PR DESCRIPTION
**Pull request by rosskevin**
- Add typescript usage tests for sanity and hook into ci to assist in keeping up to date.
- Fix several errors in the type definition

Closes #654

### CODE REVIEW

**Comment by rosskevin** [comment]
Note, this test proves and fixes a few errors I am seeing downstream in my app.  

ts users are likely broken due to the bad context type import until this is merged and released.

**Comment by rosskevin** [comment]
I'm still threading through my codebase and finding some fixes, let's hold this until I get a clean run locally.  I'll update this issue when ready.

**Comment by rosskevin** [comment]
This PR is ready to merge.

**Comment by rosskevin** [comment]
@jamuhl if we can get this merged and released, I would appreciate it.

Incorrect types included in-repo are not easily ignored, whereas they are if they are from definitelytyped (just don't include them).  This PR fixes a breaking change for ts users and should get us back to working.

**Comment by jamuhl** [comment]
published in react-i18next@9.0.1

**Comment by VincentLanglet** [comment]
@rosskevin Do you have time to test also the file for hook type ?

You broke them with your PR, cf : https://github.com/i18next/react-i18next/pull/658

**Comment by rosskevin** [comment]
@VincentLanglet I don't use the hooks yet, but feel free to add usage tests similar to how I did the index.

**Pull request merged**
