### PR TITLE
Comply with react strict mode

### PR DESCRIPTION
**Pull request by JimmyLaurent**
Replace "componentWillReceiveProps" with "getDerivedStateFromProps" in "I18nextProvider".

Fixes: #594

### CODE REVIEW

**Comment by jamuhl** [comment]
As it's only to show a warning if someone actively replaces the i18n instance - what do you think of dropping that warning? makes it simpler - and that warning i don't know how many people run into this honestly?

**Comment by JimmyLaurent** [comment]
I totally agree, it feels like an edge case.

Do you want a new PR ?

**Comment by jamuhl** [comment]
If you like and not takes to much time...else i will just remove it next time i got it open.

**Comment by jamuhl** [comment]
should be solved with https://github.com/i18next/react-i18next/commit/022b9aa5df630cb413c3e7746ecbf7569e638a9f

published on npm in react-i18next@8.3.6

**Pull request closed without merging**
