### PR TITLE
Update `t` function types to rely on types coming from i18next

### PR DESCRIPTION
**Pull request by pedrodurek**
Dependent on https://github.com/i18next/i18next/pull/1775

We'll no longer support typescript below v4.1

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [ ] run tests `npm run test`
- [ ] tests are included

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided

### CODE REVIEW

**Comment by develohpanda** [comment]
Bump, not stale! @pedrodurek what is blocking on this PR? Is there something I can do to help push it along?

For context the issue we are facing is the following, and going on the title of this PR it should fix the issue we are seeing.

image

**Review by rosskevin — CHANGES_REQUESTED** [review]
I believe this is good to go.  I'll leave a `request change` to bump the minimum i18next once https://github.com/i18next/i18next/pull/1775 is released.

Thank you @pedrodurek

**Comment by adrai** [comment]
> I believe this is good to go. I'll leave a `request change` to bump the minimum i18next once [i18next/i18next#1775](https://github.com/i18next/i18next/pull/1775) is released.
> 
> Thank you @pedrodurek

v22.0.0 is now published

**Comment by adrai** [comment]
@pedrodurek let me know when this can be merged

**Comment by adrai** [comment]
@rosskevin as soon as you approve, I'll create a new major version...

_btw: in case you're interested: https://github.com/i18next/next-i18next/pull/1966_

**Comment by adrai** [comment]
Thank you for your contributions...
v12.0.0 has just been published.

**Comment by develohpanda** [comment]
Incredible; thank you all so much for such a quick turnaround! 😍

**Pull request merged**
