### PR TITLE
Change prop-types from a peer dependency to a normal dependency

### PR DESCRIPTION
**Pull request by TLadd**
Recommended by the prop-types package: https://github.com/facebook/prop-types#how-to-depend-on-this-package

### CODE REVIEW

**Comment by jamuhl** [comment]
@TLadd do you know why this is recommended? Looks opposite to what we used to do...would be great to know the reasons - not just having a recommendation...

**Comment by TLadd** [comment]
@jamuhl Here's a few issues where this was discussed: 
https://github.com/facebook/prop-types/issues/44
https://github.com/facebook/prop-types/issues/4

With react and react-dom, the app needs to be in control of what versions are being used. Having multiple versions loaded will even break the app. With prop-types, however, there is no such restriction. As a user of the library, I don't care what version of prop-types is being used.

**Comment by jamuhl** [comment]
thank you for taking the time to pass me the additional information. Merged now. Would you need a publish of this on npm - or ok if it comes with next release?

**Comment by TLadd** [comment]
Waiting for the next release is fine with me. Thank you!

**Pull request merged**
