### PR TITLE
warn for old wait usage

### PR DESCRIPTION
**Pull request by adrai**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by felixmosh** [comment]
Currently suspense is not supported in SSR (tried in next.js), so why `useSuspense` become the standard?

**Comment by jamuhl** [comment]
@felixmosh that change was already made with v10 and looking at next-i18next there is no issue with that as suspense gets only triggered if not fulfilling prerequestitions or alternatively can be turned off

**Comment by felixmosh** [comment]
I'm using next-i18next v4 (the one that requires custom server) with Next.js v10, when disabling `wait` & enabling `useSuspense`, it throws that suspense is not supported in SSR :|

**Comment by jamuhl** [comment]
might be better to ask questions related to next.js in the next-i18next repo...can't really help with this

**Pull request merged**
