### PR TITLE
Fix type 'TFunctionResult' is not assignable to type 'ReactNode' on React 18

### LINKED ISSUE #1476: Type 'TFunctionResult' is not assignable to type 'ReactNode' on React 18
## 🐛 Bug Report

After updating to React 18, following code gives a typescript error:
```tsx
<title>{t("common:title")}</title>
       ^^^^^^^^^^^^^^^^^^^
TS2322: Type 'TFunctionResult' is not assignable to type 'ReactNode'. 
  Type 'object' is not assignable to type 'ReactNode'. 
```

## To Reproduce

https://codesandbox.io/s/react-i18next-forked-ogdrcw?file=/src/app.tsx

## Expected behavior

No error

## Your Environment

```json
  "dependencies": {
    "i18next": "21.6.14",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-i18next": "11.16.2",
    "react-scripts": "5.0.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "typescript": "4.6.2"
  },
```

### LINKED ISSUE #1477: Property 'children' does not exist on type 'IntrinsicAttributes & I18nextProviderProps' on React 18 types
## 🐛 Bug Report

After upgrading `@types/react` to `18.0.0`, the following code gives a TypeScript error.

```ts
return <I18nextProvider i18n={i18next}>{children}</I18nextProvider>;

// Type '{ children: ReactNode; i18n: i18n; }' is not assignable to type 'IntrinsicAttributes & I18nextProviderProps'.
//   Property 'children' does not exist on type 'IntrinsicAttributes & I18nextProviderProps'.ts(2322)
```

This is because the `I18nextProvider` props relies on the `children` prop implicitly being included on `React.FunctionComponent`, and this was removed in [v18 of `@types/react`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210).

## To Reproduce

https://codesandbox.io/s/react-i18next-react-18-ctvtf1

## Expected behavior

No TypeScript error.

## Your Environment

```json
"dependencies": {
  "i18next": "21.6.14",
  "react": "18.0.0",
  "react-dom": "18.0.0",
  "react-i18next": "11.16.2",
  "react-scripts": "4.0.3"
},
"devDependencies": {
  "@types/react": "18.0.0",
  "@types/react-dom": "18.0.0",
  "typescript": "4.4.2"
}
```

### PR DESCRIPTION
**Pull request by akunzai**
Fixes #1476 by add `ReactNode` to the `TDefaultResult` type

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included

### CODE REVIEW

**Comment by pedrodurek** [comment]
Hey @akunzai, the `ReactNode` should be applied on the `i18next` lib, so we can fix on both libs. https://github.com/i18next/i18next/blob/master/index.d.ts#L685

Thanks for taking the initiative!

**Comment by akunzai** [comment]
Hi @pedrodurek, thanks for the advice,
But the `i18next` has no direct dependency on the `React`,
I don't think we can apply the fix in the `i18next` repo easily.

**Comment by sergioUjo** [comment]
when will this be available to use?

**Comment by adrai** [comment]
As soon as @pedrodurek approves it

**Review by pedrodurek — APPROVED** [review]

**Comment by adrai** [comment]
v11.16.4 has just been released

**Comment by sergioUjo** [comment]
God dam that was quick, :)

**Comment by adrai** [comment]
Thanks to @akunzai for the contribution and @pedrodurek for the review.

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Pull request merged**
