### PR TITLE
Fix #247: PropTypes warnings.

### LINKED ISSUE #247: Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
warning.js?8a56:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

The above is the warning that comes after install React `v15.5`. They've moved the `PropTypes` into a separate module called `prop-types`. Please use this.

### PR DESCRIPTION
**Pull request by kadishmal**
Fix #247: PropTypes warnings.

### CODE REVIEW

**Comment by kadishmal** [comment]
1. @jamuhl how about incrementing the `react` dependency as well?
2. Will up change the version, or should I do that?

**Comment by jamuhl** [comment]
will check later when out of office and home again - thanks for providing this...really thankful for timesaving - expect it to be published later today.

**Comment by jamuhl** [comment]
1) updating deps is ok for me - normally i do them pre publish - when doing a minor version (not for all patch versions)

Will update the version of react-i18next before publishing

**Comment by jamuhl** [comment]
wonder if we should move react and prop-types to peerDependencies

**Comment by jamuhl** [comment]
just published react-i18next@3.0.0

made it major - so people are aware of needing to have prop-types installed on the main project.

**Comment by kadishmal** [comment]
@jamuhl agree on moving React and and PropTypes into peer deps.

**Pull request merged**
