### PR TITLE
fix: typescript definitions for t function without namespaces

### PR DESCRIPTION
**Pull request by pedrodurek**
Fix bugs: https://github.com/i18next/react-i18next/issues/1213 and https://github.com/i18next/react-i18next/issues/1212

In addition, I also added two examples of use and included the reference in the README file. Moreover, now that prettier is supporting typescript 4.1 (https://github.com/prettier/prettier/issues/9234) I also bumped the prettier version and run it on type definitions file.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by Thanaen** [comment]
Hi !
I've tried to apply the new TS 4.1 example, but it seems to break when a there is a key named "keys" in the translations file :-(
Here is a simple repo I used to reproduce this issue. Simply clone it, do 'yarn' then 'yarn lint' / 'yarn start' !
Here is the repository: https://github.com/Thanaen/repro-react-i18n-ts-bug

**Comment by jamuhl** [comment]
@Thanaen this looks like a different issue?!? My suggestion would be creating a new issue for that and mentioning @pedrodurek

**Comment by Thanaen** [comment]
@jamuhl Okay, creating a new issue ! Thanks for your suggestion 👍

**Comment by jamuhl** [comment]
was published in react-i18next@11.8.1

**Pull request merged**
