### PR TITLE
withTranslation() typing fix for defaultProps

### PR DESCRIPTION
**Pull request by kwieccia**
I experienced TS errors when I tried to define props interface for a component that was wrapped in `withTranslation()` and had `defaultProps`. 
 
```
interface IStepperProps extends WithTranslation {  
    isHeadless: boolean; 
    defaultStep: number;  
    isStepInvalid?: boolean;
    submitStep?: () => void;
}

class Stepper extends React.Component<IStepperProps, IStepperState> {
    static defaultProps: Partial<IStepperProps> = {
        isHeadless: true,
        defaultStep: 1,
    };
    
    (...)
} 

export default connect(mapStateToProps)(withTranslation()(Stepper));
```

The `isHeadless` and `defaultStep` props have been marked in the interface as non-optional because they were needed and always provided in `defaultProps`. But TypeScript complained if I didn't pass them in JSX for the component:

```
<Stepper>…</Stepper>

TS2739: Type '{ children: any[]; }' is missing the following properties from type 'Readonly<Pick<Pick<IStepperProps, "isHeadless" | "isStepInvalid" | "submitStep" | "defaultStep"> & WithTranslationProps, "i18n" | ... 6 more ... | "useSuspense">>': isHeadless, defaultStep 
```

After changing the `withTranslation()` typings in `index.d.ts`, [following this instruction](https://stackoverflow.com/questions/54486983/default-prop-types-through-a-higher-order-component#answer-54753991), `defaultProps` are handled properly. 

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [ ] documentation is changed or added (no need)

### CODE REVIEW

**Comment by adrai** [comment]
@pedrodurek can you review this?

**Comment by pedrodurek** [comment]
Sure!

**Comment by pedrodurek** [comment]
Hey @kwieccia, great initiative! 👏
Before I approve it, could you also update the types 4.1, please? They are under `ts4.1/index.d.ts` file. Thanks!!!

**Comment by kwieccia** [comment]
Sure thing! I pushed the updates.

**Review by pedrodurek — APPROVED** [review]
Good to go!

**Comment by jamuhl** [comment]
was published in react-i18next@11.8.4

**Pull request merged**
