### PR TITLE
fix Translation component types

### PR DESCRIPTION
**Pull request by vovsemenv**
closes https://github.com/i18next/react-i18next/issues/1508

### CODE REVIEW

**Review by pedrodurek — APPROVED** [review]
Sounds great to me! Thanks @vovsemenv

**Comment by vovsemenv** [comment]
@pedrodurek found this problem also for `withTranslation`, can you check it out too

**Comment by pedrodurek** [comment]
Sounds good!

**Comment by adrai** [comment]
sorry, in this time zone we were already sleeping...
just released v11.16.10

**Pull request merged**
