### PR TITLE
Fix runtime test while no react options.

### PR DESCRIPTION
**Pull request by jingfei**
Fix runtime test while no react i18next special options in init.

### CODE REVIEW

**Comment by jamuhl** [comment]
Wouldn't it be cleaner to change https://github.com/i18next/react-i18next/blob/master/src/context.js#L18 to

```js
export function setDefaults(options = {}) {
```

**Comment by jingfei** [comment]
I added there because `options.react` is optional. I think it depends on the design of `setDefaults`.

**Comment by jamuhl** [comment]
beside even https://github.com/i18next/react-i18next/blob/master/src/context.js#L19

```js
defaultOptions = { ...defaultOptions, ...options };
```

Does not lead to an exception when `options` is undefined 

when do you run into an issue with this?

**Comment by jingfei** [comment]
> when do you run into an issue with this?
When there's no `react` option in `init`, and get the exception since `options` is undefined. 

My opinion is maybe there exists settings which are not optional. Thus exception cannot be ignored.

**Comment by jamuhl** [comment]
options can't be undefined

external modules get called here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L92

after setting this options: https://github.com/i18next/i18next/blob/master/src/i18next.js#L40

so `instance.options` is defined and even if `instance.options.react` is undefined it can't really lead to an exception

do you call this different?!? seems really more a constructed edge case while doing something "wrong"

**Comment by jamuhl** [comment]
at least i do not get an exception here on the sample: https://github.com/i18next/react-i18next/tree/master/example/react

when removing react options here: https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js#L28

So would be great to get a sample to reproduce this is needed.

**Comment by jingfei** [comment]
Sorry it was typo, `inatance.options.react` is undefined, and get exceptions while doing `...options` in https://github.com/i18next/react-i18next/blob/master/src/context.js#L19.

FYI: Exception log
```
react-i18next/node_modules/@babel/runtime/helpers/objectSpread.js:19
      Object.defineProperties(target, Object.getOwnPropertyDescriptors(arguments[i]));
```

**Comment by jamuhl** [comment]
Just updated all dependencies -> as i guess it might be related to babel-runtime update

did a republish of react-i18next@9.0.6 does using that resolve your issue?

**Comment by jamuhl** [comment]
seems related: https://github.com/i18next/react-i18next/issues/685

**Comment by jamuhl** [comment]
should be fixed by https://github.com/i18next/react-i18next/commit/bf830d965b26ccf75afaaf6e4741cebf48d74827

in react-i18next@9.0.7 (still unclear where and why this happens...can't reproduce this in my samples)

**Comment by jingfei** [comment]
It is solved after version updated. Thank you. :)

**Pull request closed without merging**
