### PR TITLE
fix types for use()

### PR DESCRIPTION
**Pull request by rosskevin**
Depends on https://github.com/i18next/i18next/pull/1296

### CODE REVIEW

**Comment by rosskevin** [comment]
@jamuhl this can be a patch release

**Comment by jamuhl** [comment]
published in  react-i18next@10.11.5

**Comment by kuzvac** [comment]
Hi @rosskevin, today i updated all our i18next dependencies and found that types for `t` is lost, if i use withTranslation HOC. After short investigation i found that this type of import `import * as i18next from 'i18next';` is broke types definition borrowed from i18next. 
image
201909198ojz8

But if change this import just to `import i18next from 'i18next';` everything is working properly. 
I can make PR for replace `import * as i18next from 'i18next';` to `import i18next from 'i18next';` :)

**Comment by rosskevin** [comment]
@kuzvac please see https://github.com/i18next/react-i18next/issues/931#issuecomment-526636217 or file a new PR with a breaking test case. This is thoroughly tested.

**Comment by kuzvac** [comment]
@rosskevin thanks. hmmm... react-i18next test is working properly with our tsconfig & tslint files. Looks like it's problem with our code/dependencies :)

**Comment by kuzvac** [comment]
@rosskevin I found why the error occurs in my case :) 
I do clean install, compare version of i18next modules, and found that, in version that doesn't work, i have `i18next^15.1.3` and `react-i18next^10.12.5`
What a mess, shame on me 😅

**Pull request merged**
