### PR TITLE
Added Type Definitions

### PR DESCRIPTION
**Pull request by schettino**
_For future releases, feel free to ping me to get the typings updated_

Resolves: #550 

This PR adds the typescript type definitions.

hoc usage
```javascript
interface Props extends WithNamespaces {}

export default withNamespaces()<Props>(AddressField);
```

### CODE REVIEW

**Comment by jamuhl** [comment]
Awesome. Thanks a lot. Was published with react-i18next@8.1.0

Hope i will remember pinging you in case we need to change the definitions - will need to start remembering this.

**Comment by schettino** [comment]
Anytime @jamuhl. I'll be looking at the issues in case of something related to the typings comes up, and new releases as well. Thanks

**Comment by mgroenhoff** [comment]
Is anyone deleting the types from DT already?

**Comment by mgroenhoff** [comment]
Is anyone deprecating DT typings https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-i18next  already?

**Comment by mgroenhoff** [comment]
Is anyone deprecating DT typings https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-i18next  already?

**Comment by mgroenhoff** [comment]
Is anyone deprecating DT typings https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-i18next  already?

**Comment by mgroenhoff** [comment]
Is anyone deprecating DT typings https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-i18next  already?

**Comment by beheh** [comment]
I'll file a PR against DT.

**Comment by brandonhall** [comment]
@schettino Thanks for doing this!

**Comment by chillitom** [comment]
I'm getting the following error after upgrading to use the type definitions from 8.1.0.

```
C:/code/node_modules/react-i18next/index.d.ts
(2,8): Module '"C:/code/node_modules/@types/i18next/index"' has no default export.

```

**Comment by mgroenhoff** [comment]
> I'm getting the following error after upgrading to use the type definitions from 8.1.0.
> 
> ```
> C:/code/node_modules/react-i18next/index.d.ts
> (2,8): Module '"C:/code/node_modules/@types/i18next/index"' has no default export.
> ```
> I have the latest `i18next` module and types installed.

@chillitom The types are written in such a way that it requires the compiler option `allowSyntheticDefaultImports` to be enabled an depending on the target version maybe also `esModuleInterop`.

**Comment by jamuhl** [comment]
@jchu231 @mgroenhoff please create a new issue if having problem - adding comments to closed PR might risk that gets under the table (forgotten)

**Pull request merged**
