### PR TITLE
use optional chaining, nullish coalescing and nullish coalescing assignment

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Uses optional chaining, nullish coalescing and nullish coalescing assignments to reduce property access, truthy check and streamline code.

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Ah I accidentally committed the build assets as well, is that a problem or should I remove them?

**Comment by adrai** [comment]
Better removing them

**Comment by adrai** [comment]
Should we release a new major version now, or do you like to change something else?

**Comment by VIKTORVAV99** [comment]
> Should we release a new major version now, or do you like to change something else?

There is that other PR that changes how the namespaces are loaded at #1770 but the existing code are not really working as sometimes the function that is called though the passed object is undefined. I'll see if I can fix it tomorrow or just leave it for the next major release if I don't solve it or don't have time to solve it tomorrow.

If I can't solve it by then how would you feel about converting the project to TypeScript so it's easier to debug and track down the issues in the future?

**Comment by adrai** [comment]
Ok, will wait for tomorrow, and also check for that hasLoadedNamespace functionality...
Regarding TypeScript, please no.

**Comment by adrai** [comment]
waiting for your "GO" to create a new major release

**Comment by VIKTORVAV99** [comment]
> waiting for your "GO" to create a new major release

Feel free to do so, I have no other breaking changes I want to do. Any potential changes going forward will just be improvements that are non breaking.

**Comment by adrai** [comment]
v15.0.0 has just been relesed

**Comment by VIKTORVAV99** [comment]
Very nice!

**Pull request merged**
