### PR TITLE
Dependabot configuration

### PR DESCRIPTION
**Pull request by mmorel-35**
Define dependabot to keep npm dependencies and github action up-to-date

### CODE REVIEW

**Comment by adrai** [comment]
personally not a fan of automatic dependency updates

**Comment by mmorel-35** [comment]
Hi @adrai , why do you think that? With dependabot, the update is proposed automatically, it creates a PR and passes your ci testing like any other PR you woul receive . You can always reject the PR if you don't want it.

**Comment by adrai** [comment]
Just my personal opinion...
usually when creating a new version I check for new dependency versions with npm-check-update...

**Comment by mmorel-35** [comment]
I see...

**Pull request closed without merging**
