### PR TITLE
Added support for keyComponents prop in Trans component

### PR DESCRIPTION
**Pull request by iamrane**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by iamrane** [comment]
Is this exceeding the limit of lines per file something I need to deal with. Will lead to me refactoring code I didn’t write. Or can you approve a PR without me resolving this issue?

**Comment by jamuhl** [comment]
I don't like the approach of mutating the value in the resourcestore to much...why not just convert that stuff here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L114 before the interpolation replaces those interpolationVariables?

calling the new prop: `keyComponents` not sure if that is not misleading (i18n keys, what are key components) -> eventual something like `interpolationWrappers` would be better?

Beside that - not sure what the end of discussion https://github.com/i18next/react-i18next/issues/1308#issuecomment-831017220 is - perhaps a few more community opinions would help...

**Comment by iamrane** [comment]
> I don't like the approach of mutating the value in the resourcestore to much...why not just convert that stuff here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L114 before the interpolation replaces those interpolationVariables?
> 
> calling the new prop: `keyComponents` not sure if that is not misleading (i18n keys, what are key components) -> eventual something like `interpolationWrappers` would be better?
> 
> Beside that - not sure what the end of discussion [#1308 (comment)](https://github.com/i18next/react-i18next/issues/1308#issuecomment-831017220) is - perhaps a few more community opinions would help...

Yeah I agree on that changing the resource feels "bad". I didn't deep dive in the code that hard. Thanks for pointing out where in the code I can have a look. Will look into it later on.

**Comment by iamrane** [comment]
So i updated the Trans component now so the I don't manipulate the resource.
And I also moved in the manipulation to where @jamuhl guided me.

**Comment by iamrane** [comment]
Hi!
I will close this PR, i values is not really a simple key-value relation it can be so much more. You can add formatters in the resource string etc. So its not really techical possible to do it how I want it im afraid.

I will need to use components instead. Thanks any way.

**Pull request closed without merging**
