### PR TITLE
Fix default lang bug when React tree doesn't contain withI18next

### PR DESCRIPTION
**Pull request by isaachinman**

### CODE REVIEW

**Comment by jamuhl** [comment]
thank you for looking deeper into it...really appreciate your help.

personal i'm looking into the 16.7 release of react -> guess will bring some changes to next.js too

**Comment by isaachinman** [comment]
Yup, it probably does. I haven't looked at 16.7 yet, but I might get a chance to this week. Just let me know if you need anything!

**Comment by jamuhl** [comment]
prepared a react-i18next version based on hooks and suspense (no support for SSR yet) -> if you ever into it you might have a look: https://github.com/i18next/react-i18next/issues/590

**Comment by isaachinman** [comment]
Nice! I will take a look sometime this week.

**Comment by Enalmada** [comment]
@isaachinman When I run the latest nextjs example from master, clicking any link appears to do a full page change and flicker.

**Pull request merged**
