### PR TITLE
Fix/bug 1691 make returned t function identical upon second effect run in strict mode

### PR DESCRIPTION
**Pull request by timheilman**
#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [ ] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
@medihack can you review this?

**Comment by timheilman** [comment]
https://github.com/testing-library/react-testing-library/pull/1241 was _just_ merged, but I haven't looked closely yet at it to see if hook-based testing support was added for useEffect double-run in strictMode

**Comment by timheilman** [comment]
OK, I went down a bit of a rabbit hole toward writing a unit test for this, but it looks like strictMode is integrated into @testing-library/react (which subsumed @testing-library/react-hooks) only for v18 of react and higher, whereas react-i18next is still supporting v16 of react. That precludes using the strictMode testing configuration, without which it's hard for me to see how to test this change otherwise than as described in the "To Reproduce" section of the [issue](https://github.com/i18next/react-i18next/issues/1691). That reproduction is reliable and is indeed fixed by this change.

**Comment by adrai** [comment]
ok, no test required, but I like @medihack to check if this change will influence in some way the issue he had [here](https://github.com/i18next/react-i18next/issues/1272#issuecomment-791745096)

**Comment by adrai** [comment]
//cc: @kachkaev

**Comment by timheilman** [comment]
> ok, no test required, but I like @medihack to check if this change will influence in some way the issue he had [here](https://github.com/i18next/react-i18next/issues/1272#issuecomment-791745096)

I totally understand.  This is a widely-depended-upon library that I'm certainly no expert with. I welcome any/all code review comments and/or edits by those more familiar with the code.

The test @medihack added alongside the change for the issue of changing the provider-provided i18n instance _is_ still passing, which is a good sign. This makes sense since the `useCallback` memoization _does_ have that `i18n` instance in its dependency list, and so should generate a new fixedT. However, the truth is that I'm not very familiar at all with this code, and it is hairy, so I still very much welcome more experienced eyes on it.

**Comment by medihack** [comment]
At first glance, it looks good. If there is no time pressure, I would take a deeper look and try it out on the weekend if that is ok for you.

**Comment by adrai** [comment]
wonderful... thank you @medihack

**Comment by medihack** [comment]
The PR looks good to me. I also gave it a quick test drive and got no problems (with shallow routing in Next.js).

**Comment by adrai** [comment]
Thank you very much for your contributions... it's included in v14.0.2

**Comment by jaredhan418** [comment]
Why!!!!!! Why!!!!! Damn!
`i18n.changeLanguage` will never work immediately in every env!
StrictMode is so damn bad!

**Comment by adrai** [comment]
@jaredhan418 is right... this PR breaks the language change rendering... @timheilman can you have a look at it? @medihack can you assist?

**Comment by adrai** [comment]
I temporarily reverted it with v14.0.3

**Comment by medihack** [comment]
That's unfortunate :-( And unfortunately, I don't have enough time right now. I'll try my best in the upcoming weeks, but it looks like a nasty issue to fix entirely.

**Comment by timheilman** [comment]
happy to take a look! Though of course I can't promise anything.  Thanks @jaredhan418 for your testing and notifying of the breakage, and thanks @adrai for being so on-top of this repo.  Reversion is obviously the right move.

**Pull request merged**
