### PR TITLE
Escape non breaking space

### PR DESCRIPTION
**Pull request by predragnikolic**
This should address this comment https://github.com/i18next/react-i18next/issues/1428#issuecomment-992566188

**This is a try I am not sure if this works.**
I do not know how to test this manually locally. I run the tests `npm run test`, and the test are passing so that makes me think that everthing should work...

So feel free to push some commits.

#### Checklist

- [X] only relevant code is changed (make a diff before you submit the PR)
- [X] run tests `npm run test`
- [X] tests are included

#### Checklist (for documentation change)

- [ ] only relevant documentation part is changed (make a diff before you submit the PR)
- [ ] motivation/reason is provided

### CODE REVIEW

**Comment by adrai** [comment]
@cuyl can you review this?

**Comment by cuyl** [comment]
@adrai `&nbsp;` is work without any changes.

@predragnikolic  You can revert `react-i18next.js` change and run test, it works.

**Comment by predragnikolic** [comment]
> &nbsp; is works without any changes.

Are you sure?

I have the following:
```
<Trans
    shouldUnescape
    defaults={"<p>Do&nbsp;Not&nbsp;Disturb</p>"} />
```

And I expect to see:
Screen Shot 2021-12-14 at 2 07 07 PM


But I see:
Screen Shot 2021-12-14 at 2 06 40 PM

**Comment by adrai** [comment]
@predragnikolic this works without any change: https://github.com/i18next/react-i18next/commit/71d3542d9132cd679ae9af4f2fb8e8e0ad24127f

**Comment by predragnikolic** [comment]
> this works without any change:

True the test passes even without my changes, 
but I am confused why the browser still displays `&nbsp`;

**Comment by cuyl** [comment]
@predragnikolic If you want render many actual spaces, you can try `\u00A0` or `\xA0`. unescape `&nbsp;` to `SPACE` can't help you, because even you unescape `&nbsp;` to `SPACE`, html still only render one space.

**Comment by predragnikolic** [comment]
I'd say that I expected the wrong behavior, so I'm closing this. :)

**Pull request closed without merging**
