### PR TITLE
Fix Trans component ignore default options

### PR DESCRIPTION
**Pull request by yashigani**
react-i18next has some default options but Trans component ignore it.
Reproduce it project: https://codesandbox.io/s/1zxox032q

### CODE REVIEW

**Comment by jamuhl** [comment]
Hm...now you ignore the passed in options

if need defaults + passed in it should be:

```js
init(instance) {
    setDefaults({ ...getDefaults(), ...instance.options.react});	    
    setI18n(instance);
  },
};
```

**Comment by yashigani** [comment]
I seem `setDefaults` method merge options into `defaultOptions`.

```
export function setDefaults(options = {}) {
  defaultOptions = { ...defaultOptions, ...options };
}
```

**Comment by jamuhl** [comment]
right...i see now what you mean...the Trans component also takes stuff from i18nextOptions directly...for cases passed in i18n via props but using "setDefaults" does not change your options...

guess will merge options in Trans...please keep this open...will provide a fix asap

**Comment by jamuhl** [comment]
should be fixed in react-i18next@10.6.2

**Pull request closed without merging**
